### ISSUE TITLE
Provide one .mtx file per project

### ISSUE THREAD

**Issue by theathorn** [DailyDreaming/load-project#10]
Convert csv matrix files to mtx format.

**Comment by hannes-ucsc** [comment]
@noah-aviel-dove to create functions for 1) converting csv to mtx and 2) to merge multiple mtx into one.

@jessebrennan to apply those functions to each project as appropriate.

**Comment by hannes-ucsc** [comment]
Closing in favour of #43, #44, #45, and #46.
