### ISSUE TITLE
Import SCXA projects

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#111]
Step 1: Come up with a design how this would work, write it down here and discuss with @hannes-ucsc.

**Comment by jessebrennan** [comment]
## Plan

There are two main steps:
- download the files from SCXA
- map the metadata for the SCXA projects to our metadata model

Every project has MatrixMarket format matrices available to download, so we won't need to do any matrix conversion. The cell counts are provided, but also could be derived using our current mechanism from the matrices.

I'm going to start with the downloading first. Then it will be more straightforward to look at the downloaded files and come up with the best solution for converting the metadata.
