### ISSUE TITLE
Cite tsne plot sources.

### ISSUE THREAD

**Issue by DailyDreaming** [DailyDreaming/load-project#117]
There are plenty of charts and graphs in the browser: https://ux-dev.data.humancellatlas.org/explore/projects/099c02da-23b2-5748-8618-92bc6770dc51/expression-matrices

But we don't say where they came from.  We should add a citation for their source and/or specify what tool(s) was used to generate them if made in-house.

**Comment by theathorn** [comment]
Citation now embedded in the png.
