### ISSUE TITLE
First argument to IndividualCellFiles constructor should be as specific as possible

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#125]
https://github.com/DailyDreaming/load-project/blob/012081777170c36961ca9ffd2e92dfd9da1f09b0/convert_matrices.py#L1375

Should read `IndividualCellFiles('GSE110154_RAW/cell_files')`

**Comment by nadove-ucsc** [comment]
I believe this is invalid because `cell_files` is not part of the path.

**Comment by hannes-ucsc** [comment]
You are correct. I created this under while under the impression that `cell_files` was a component of the actual path underneath the `geo` directory, not realizing that it is in fact synthetic.
