### ISSUE TITLE
atomic_gzip_file truncates file contents

### ISSUE THREAD

**Issue by nadove-ucsc** [DailyDreaming/load-project#131]
A malformed loop causes the first megabyte of the file being compressed to be lost.

**Comment by hannes-ucsc** [comment]
Also ran `make clean_matrices` and `make matrices` with `SKUNK_ACCESSIONS="GSE103275,GSE103354,GSE106273,GSE108291,GSE114802,GSE117089,GSE124472,GSE124494,GSE126836,GSE129798,GSE130430,GSE130606,GSE131685,GSE132044,GSE96583"` set.
