### ISSUE TITLE
Recursively extract all GEO tarballs

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#3]

**Comment by dsotirho-ucsc** [comment]
Download of all GEO accession supplementary files has been completed.
With https://github.com/DailyDreaming/load-project/pull/11 symlinks have been created pointing the accession id (symlink) to the project uuid (folder).
With https://github.com/DailyDreaming/load-project/pull/12 tar files will be extracted for processing

**Comment by hannes-ucsc** [comment]
https://github.com/DailyDreaming/load-project/pull/37
