### ISSUE TITLE
Total donor and specimen counts are zero

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#39]
![image](https://user-images.githubusercontent.com/5143256/71755211-712f5980-2e3e-11ea-8482-ad925ffa79fd.png)

**Comment by DailyDreaming** [comment]
This appears to be solved: https://ux-dev.data.humancellatlas.org/explore/projects

**Comment by hannes-ucsc** [comment]
What you see now in ux-dev is an experiment with code I haven't committed yet. I'll close this once I can refer to commit.
