### ISSUE TITLE
Broken links to external resources

### ISSUE THREAD

**Issue by DailyDreaming** [DailyDreaming/load-project#57]
All `external resources` links appear to be broken:  https://ux-dev.data.humancellatlas.org/explore/projects/8d1bf054-faad-5ee8-a67e-f9b8f379e6c3/external-resources

`Traceback (most recent call last): File "/var/task/chalice/app.py", line 1104, in _get_view_function_response response = view_function(**function_args) File "/var/task/app.py", line 464, in get_integrations body = _fetch_integrations(entity_type, integration_type, entity_ids) File "/var/task/app.py", line 485, in _fetch_integrations for integration in cast(Sequence[JSON], portal['integrations']) File "/var/task/app.py", line 486, in if integration['entity_type'] == entity_type and integration['integration_type'] == integration_type File "/var/task/app.py", line 484, in {k: v if k != 'entity_ids' else v[config.dss_deployment_stage] for k, v in integration.items()} KeyError: 'dev' 
`

**Comment by achave11-ucsc** [comment]
PR with fix in Azul: [#1508](https://github.com/DataBiosphere/azul/pull/1508)

**Comment by achave11-ucsc** [comment]
Assigning @hannes-ucsc  for review!

**Comment by hannes-ucsc** [comment]
I requested changes.

**Comment by achave11-ucsc** [comment]
Addressed requested changes!
