### ISSUE TITLE
 Create statistics for cumulative cell counts over time

### ISSUE THREAD

**Issue by theathorn** [DailyDreaming/load-project#60]
BrianO: I haven't seen something like cumulative cell counts over time.  Is that something you can easily do?  E.g. we have the cell counts per project and, presumably, dates for when those projects were onboarded.  Can you create for me a plot like this?  Also, projects onboarded over time could be made at the same time.

Note: this would have to be from the prod deployment which is the only one with long term data.

**Comment by DailyDreaming** [comment]
@amarjandu https://github.com/DailyDreaming/load-project/tree/master/.attic might be helpful.

**Comment by amarjandu** [comment]
https://docs.google.com/spreadsheets/d/1AKVIPG6TQ0FmQBGg_C41KYQmdcO2IuV9_fslTTzoZ_8/edit?usp=sharing

**Comment by amarjandu** [comment]
Closed by #62
