### ISSUE TITLE
Add ability to limit working set for all scripts

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#87]
All script should process an environment variable call SKUNK_ACCESSIONS containing a comma-separated list of GEO series accessions. If that variable is set, only the specified accessions should be processed. If that variable is empty, no accessions should be processed. If that variable is unset, all accessions should be processed.

**Comment by nadove-ucsc** [comment]
In progress, currently untested: https://github.com/DailyDreaming/load-project/tree/issues/noah-aviel-dove/87-limit-working-set

Open to feedback regarding algorithmic correctness while instance is offline

**Comment by nadove-ucsc** [comment]
https://github.com/DailyDreaming/load-project/pull/98
