### ISSUE TITLE
Survey additional GEO and SCXA projects

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#92]
Determine which GEO projects we could add, and estimate what it would take to get the metadata for those projects. Ask for advice from wranglers.

Survey the [SCXA](https://www.ebi.ac.uk/gxa/sc/home) projects and determine if we can obtain metadata and matrix files for them.

**Comment by jessebrennan** [comment]
It seems like getting data from SCXA should be pretty straight forward. MatrixMarket files and metadata are available for download on the site. The metadata is in an unfamiliar format SDRF and IDF files, but after a cursory glance it shouldn't be that difficult to parse.

**Comment by DailyDreaming** [comment]
Linking in my new favorite website: https://panglaodb.se/index.html

They have tsne plots that we don't have too.  @noah-aviel-dove Knows about this.

**Comment by jessebrennan** [comment]
![20200116_170517](https://user-images.githubusercontent.com/10734740/72576365-58826300-3884-11ea-8edb-9e175d546eda.jpg)
